---
name: "Publish to preview server"
description: "Update kubernetes deployment image"
inputs:
  kairos_url:
    description: "Publish endpoint"
    required: true
  kairos_token:
    description: "Authentication token to be able to upload artifacts"
    required: true
  zipfile:
    description: "Zip file that contains all the assets to be published"
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload compiled output
      shell: bash
      run: |
        full_hash=$GITHUB_SHA
        file="${full_hash:0:7}.zip"
        mv ${{ inputs.zipfile }} $file
        response=$(curl -D headers.txt -X POST -H "X-Api-Token:${{ inputs.kairos_token }}" -F "file=@$file" ${{ inputs.kairos_url }})
        echo "Checking Kairo response..."
        echo "HEADERS\n$(cat headers.txt)"
        echo "RESPONSE\n$response"
        cat headers.txt | grep " 200" || exit 1
        echo "preview_url=$response" >> $GITHUB_ENV

    - uses: actions/checkout@v4

    - name: Build body comment
      shell: bash
      run: |
        ls -la
        whoami
        git config --global --add safe.directory /__w/playbook/playbook
        for file in $(git show --pretty="" --name-only HEAD | grep ".md" | sed s/.md$//); do
          inner=$(echo "$file" | sed s/^content// | sed s/.md$//)
          echo "- $preview_url$inner"
        done >links.txt
        echo "preview_body=$(cat links.txt)" >> $GITHUB_ENV

    - name: Notify preview URL into PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Previews:\n ${{ env.preview_body }}'
          })
